export const ADDISON_PREVIEW_ARRIVALS = [
  {
    id: "brn-411-kimball",
    routeColor: "var(--color-line-brown)",
    routeLabel: "Brown Line",
    runNumber: "411",
    destinationName: "Kimball",
    etaValue: "8",
    etaUnit: "min",
    textColor: "var(--color-text-on-route)",
    copyColor: "var(--color-text-secondary)",
  },
  {
    id: "brn-412-loop",
    routeColor: "var(--color-line-brown)",
    routeLabel: "Brown Line",
    runNumber: "412",
    destinationName: "Loop",
    etaValue: "12",
    etaUnit: "min",
    textColor: "var(--color-text-on-route)",
    copyColor: "var(--color-text-secondary)",
  },
  {
    id: "brn-404-kimball",
    routeColor: "var(--color-line-brown)",
    routeLabel: "Brown Line",
    runNumber: "404",
    destinationName: "Kimball",
    etaValue: "21",
    etaUnit: "min",
    textColor: "var(--color-text-on-route)",
    copyColor: "var(--color-text-secondary)",
  },
  {
    id: "brn-405-loop",
    routeColor: "var(--color-line-brown)",
    routeLabel: "Brown Line",
    runNumber: "405",
    destinationName: "Loop",
    etaValue: "32",
    etaUnit: "min",
    textColor: "var(--color-text-on-route)",
    copyColor: "var(--color-text-secondary)",
  },
] as const;
